### ISSUE TITLE
dotjs version lacks the CSS code

### ISSUE THREAD

**Issue by lucasmazza** [nashby/jose-vs-oss#22]
I use this extension on Safari through dotjs, but since we depend on the CSS code to align the buttons properly the JS file does not have all the code required to run it like the Chrome extension. Maybe we could provide a standalone script that injects the CSS styles instead of requiring another file to be loaded by the browser.

Something like this does the job for me:

```ruby
coffee = File.read('jose.coffee')
styles = File.read('jose.css')

css = <<-CODE
node = document.createElement('style')
node.innerHTML = "#{styles}"
document.body.appendChild(node)
CODE

File.open('merged.coffee', 'w') { |io| io.write(css + coffee) }
system 'coffee -c merged.coffee && rm merged.coffee && mv merged.js ~/.js/github.com.js'
```

**Comment by nashby** [comment]
@lucasmazza makes sense, thanks! I'll try to come with something tonight.

**Comment by nashby** [comment]
@lucasmazza yo I jsut made css inline. Can you please test it?

**Comment by lucasmazza** [comment]
@nashby :+1: :shipit:
